site_name: B1-Docs
site_description: >-
  B1-Docs is a documentation site for Burn-One-Studios projects.
site_author: Burn-One-Studios
site_url: https://docs.burnonestudios.com

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
      primary: orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to light mode    
      primary: deep orange
      accent: deep purple
  font:
    text: Source Code Pro
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Burn-One-Studios
    - icon: fontawesome/brands/discord
      link: https://discord.gg/burnone


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - abbr
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - FiveM Resources:
    - B1-Skillz:
      - FiveM-Resources/B1-skillz/Installation Guide.md
      - UpdateSkill: FiveM-Resources/B1-skillz/UpdateSkill.md
      - CheckSkill: FiveM-Resources/B1-skillz/CheckSkill.md
      - GetCurrentSkill: FiveM-Resources/B1-skillz/GetCurrentSkill.md


copyright: |
  &copy; 2023 <a href="https://github.com/Burn-One-Studios"  target="_blank" rel="noopener">Burn-One-Studios</a>